/*
禁止修改!此文件是产品代码的一部分，后续可能变更或者不再开放。
若有问题，请参考前端相关二开文档。
*/
const mockParticipant = {
  name: '当前处理人',
  name_i18n: { en: 'Current Approver', zh: '当前处理人' },
  propertyCode: 'participants_',
  code: 'participants_',
  propertyType: 51,
  propertyName: '当前处理人',
  dataIndex: 'participants_',
  isSystem: true,
  type: 51,
  scopedSlots: { customRender: 'participants_' },
  relativeSchemaCode: null,
  childColumns: null,
  data: {
    name: '当前处理人',
    name_i18n: { en: '当前处理人', zh: '当前处理人' },
    propertyCode: 'participants_',
    code: 'participants_',
    propertyType: 51,
    propertyName: '当前处理人',
    dataIndex: 'participants_',
    isSystem: true,
    type: 51,
    scopedSlots: { customRender: 'participants_' },
    relativeSchemaCode: null,
    childColumns: null,
    schemaCode: 'xjl_DonePerson',
    choiceType: 1,
    defaultValue: '',
    displayType: 0,
    endValue: '',
    startValue: '',
    options: null,
    visible: true,
    relativeQueryCode: '',
    defaultState: 1,
    accurateSearch: false,
    dateType: 0,
    sortKey: 2,
    userOptionType: 1,
    checked: false,
    hoverClass: false,
    direction: 1,
    width: '162',
    unit: null,
    sumType: null,
    displayFormat: 2,
    popover: false,
    isQueryColumn: true,
    id: 'afeb204e800883b701800cd836d50233',
    remarks: null,
    createdTime: '2022-04-09 13:42:18',
    modifiedTime: '2022-04-10 17:58:20',
    deleted: false,
    createdBy: null,
    modifiedBy: 'afeb204e7fb075c7017fb102fb0005f3',
    isDefaultProperty: true,
    queryId: 'afeb204e800883b701800cd836a4022f',
    clientType: 'PC',
    schemaAlias: 'a_1',
    propertyAlias: 'participants_',
    syncDefaultFormat: false,
    displayFields: null,
    queryLevel: 1,
    data: '__vue_devtool_undefined__',
  },
  schemaCode: 'xjl_DonePerson',
  choiceType: 1,
  defaultValue: '',
  displayType: 0,
  endValue: '',
  startValue: '',
  options: null,
  visible: true,
  relativeQueryCode: '',
  defaultState: 1,
  accurateSearch: false,
  dateType: 0,
  sortKey: 2,
  userOptionType: 1,
  checked: false,
  hoverClass: false,
  direction: 1,
  width: '162',
  unit: null,
  sumType: null,
  displayFormat: 2,
  popover: false,
  isQueryColumn: true,
  id: 'afeb204e800883b701800cd836d50233',
  remarks: null,
  createdTime: '2022-04-09 13:42:18',
  modifiedTime: '2022-04-10 17:58:20',
  deleted: false,
  createdBy: null,
  modifiedBy: 'afeb204e7fb075c7017fb102fb0005f3',
  isDefaultProperty: true,
  queryId: 'afeb204e800883b701800cd836a4022f',
  clientType: 'PC',
  schemaAlias: 'a_1',
  propertyAlias: 'participants_',
  syncDefaultFormat: false,
  displayFields: null,
  queryLevel: 1,
  published: true,
};

export default mockParticipant;
