/*
禁止修改!此文件是产品代码的一部分，后续可能变更或者不再开放。
若有问题，请参考前端相关二开文档。
*/
export const controlAttributeListMap = {
  '1': [
    {
      label: '最大长度',
      title: '最大长度',
      key: 'maxLength',
      index: 1,
      type: 'string',
      value: 200,
      isRuleAttribute: 1,
    },
    {
      label: '正则校验',
      title: '正则校验',
      key: 'regexp',
      index: 2,
      type: 'string',
      value: '',
      isRuleAttribute: 1,
    },
    {
      label: '正则错误提示',
      title: '正则错误提示',
      key: 'regexpText',
      index: 3,
      type: 'string',
      value: '',
      isRuleAttribute: 1,
    },
    {
      label: '计算规则',
      title: '计算规则',
      key: 'shortTextStitch',
      index: 4,
      type: 'string',
      value: '',
      isRuleAttribute: 1,
    },
    {
      label: '数据字典',
      title: '数据字典',
      key: 'dictionaryData',
      index: 5,
      type: 'string',
      value: '',
      isRuleAttribute: 2,
      isNotShowHis: true,
    },
    {
      label: '去重校验',
      title: '去重校验',
      key: 'noRepeat',
      index: 6,
      type: 'string',
      value: '',
      isRuleAttribute: 1,
    },
    {
      label: '显示条件',
      title: '显示条件',
      key: 'displayFormula',
      index: 7,
      type: 'string',
      value: '',
      isRuleAttribute: 1,
    },
    {
      label: '只读条件',
      title: '只读条件',
      key: 'readonlyCondition',
      index: 8,
      type: 'string',
      value: '',
      isRuleAttribute: 1,
    },
    {
      label: '是否必填',
      title: '是否必填',
      key: 'requiredFormula',
      index: 9,
      type: 'string',
      value: '',
      isRuleAttribute: 1,
    },
  ],
  '2': [
    {
      label: '最大长度',
      title: '最大长度',
      key: 'maxLength',
      index: 1,
      type: 'string',
      value: 2000,
      isRuleAttribute: 1,
    },
    {
      label: '正则校验',
      title: '正则校验',
      key: 'regexp',
      index: 2,
      type: 'string',
      value: '',
      isRuleAttribute: 1,
    },
    {
      label: '正则错误提示',
      title: '正则错误提示',
      key: 'regexpText',
      index: 3,
      type: 'string',
      value: '',
      isRuleAttribute: 1,
    },
    {
      label: '计算规则',
      title: '计算规则',
      key: 'shortTextStitch',
      index: 4,
      type: 'string',
      value: '',
      isRuleAttribute: 1,
    },
    {
      label: '显示条件',
      title: '显示条件',
      key: 'displayFormula',
      index: 5,
      type: 'string',
      value: '',
      isRuleAttribute: 1,
    },
    {
      label: '只读条件',
      title: '只读条件',
      key: 'readonlyCondition',
      index: 6,
      type: 'string',
      value: '',
      isRuleAttribute: 1,
    },
    {
      label: '是否必填',
      title: '是否必填',
      key: 'requiredFormula',
      index: 7,
      type: 'string',
      value: '',
      isRuleAttribute: 1,
    },
  ],
  '3': [
    {
      label: '默认格式',
      title: '默认格式',
      key: 'format',
      index: 1,
      type: 'string',
      value: '',
      isRuleAttribute: 2,
      isNotShowHis: true,
    },
    {
      label: '计算规则',
      title: '计算规则',
      key: 'shortTextStitch',
      index: 2,
      type: 'string',
      value: '',
      isRuleAttribute: 1,
    },
    {
      label: '提交校验规则',
      title: '提交校验规则',
      key: 'verifyFormula',
      index: 3,
      type: 'string',
      value: '',
      isRuleAttribute: 1,
    },
    {
      label: '显示条件',
      title: '显示条件',
      key: 'displayFormula',
      index: 4,
      type: 'string',
      value: '',
      isRuleAttribute: 1,
    },
    {
      label: '只读条件',
      title: '只读条件',
      key: 'readonlyCondition',
      index: 5,
      type: 'string',
      value: '',
      isRuleAttribute: 1,
    },
    {
      label: '是否必填',
      title: '是否必填',
      key: 'requiredFormula',
      index: 6,
      type: 'string',
      value: '',
      isRuleAttribute: 1,
    },
  ],
  '4': [
    {
      label: '默认格式',
      title: '默认格式',
      key: 'format',
      index: 1,
      type: 'string',
      value: '',
      isRuleAttribute: 2,
      isNotShowHis: true,
    },
    {
      label: '计算规则',
      title: '计算规则',
      key: 'shortTextStitch',
      index: 2,
      type: 'string',
      value: '',
      isRuleAttribute: 1,
    },
    {
      label: '提交校验规则',
      title: '提交校验规则',
      key: 'verifyFormula',
      index: 3,
      type: 'string',
      value: '',
      isRuleAttribute: 1,
    },
    {
      label: '显示条件',
      title: '显示条件',
      key: 'displayFormula',
      index: 4,
      type: 'string',
      value: '',
      isRuleAttribute: 1,
    },
    {
      label: '只读条件',
      title: '只读条件',
      key: 'readonlyCondition',
      index: 5,
      type: 'string',
      value: '',
      isRuleAttribute: 1,
    },
    {
      label: '是否必填',
      title: '是否必填',
      key: 'requiredFormula',
      index: 6,
      type: 'string',
      value: '',
      isRuleAttribute: 1,
    },
  ],
  '5': [
    {
      label: '选项',
      title: '选项',
      key: 'options',
      index: 1,
      type: 'string',
      value: '',
      isRuleAttribute: 2,
    },
    {
      label: '显示条件',
      title: '显示条件',
      key: 'displayFormula',
      index: 2,
      type: 'string',
      value: '',
      isRuleAttribute: 1,
    },
    {
      label: '只读条件',
      title: '只读条件',
      key: 'readonlyCondition',
      index: 3,
      type: 'string',
      value: '',
      isRuleAttribute: 1,
    },
    {
      label: '是否必填',
      title: '是否必填',
      key: 'requiredFormula',
      index: 4,
      type: 'string',
      value: '',
      isRuleAttribute: 1,
    },
  ],
  '6': [
    {
      label: '选项',
      title: '选项',
      key: 'options',
      index: 1,
      type: 'string',
      value: '',
      isRuleAttribute: 2,
    },
    {
      label: '显示条件',
      title: '显示条件',
      key: 'displayFormula',
      index: 2,
      type: 'string',
      value: '',
      isRuleAttribute: 1,
    },
    {
      label: '只读条件',
      title: '只读条件',
      key: 'readonlyCondition',
      index: 3,
      type: 'string',
      value: '',
      isRuleAttribute: 1,
    },
    {
      label: '是否必填',
      title: '是否必填',
      key: 'requiredFormula',
      index: 4,
      type: 'string',
      value: '',
      isRuleAttribute: 1,
    },
  ],
  '7': [
    {
      label: '选项',
      title: '选项',
      key: 'options',
      index: 1,
      type: 'string',
      value: '',
      isRuleAttribute: 2,
    },
    {
      label: '显示条件',
      title: '显示条件',
      key: 'displayFormula',
      index: 2,
      type: 'string',
      value: '',
      isRuleAttribute: 1,
    },
    {
      label: '只读条件',
      title: '只读条件',
      key: 'readonlyCondition',
      index: 3,
      type: 'string',
      value: '',
      isRuleAttribute: 1,
    },
    {
      label: '是否必填',
      title: '是否必填',
      key: 'requiredFormula',
      index: 4,
      type: 'string',
      value: '',
      isRuleAttribute: 1,
    },
  ],
  '8': [
    {
      label: '显示条件',
      title: '显示条件',
      key: 'displayFormula',
      index: 1,
      type: 'string',
      value: '',
      isRuleAttribute: 1,
    },
    {
      label: '只读条件',
      title: '只读条件',
      key: 'readonlyCondition',
      index: 2,
      type: 'string',
      value: '',
      isRuleAttribute: 1,
    },
  ],
  '9': [
    {
      label: '显示条件',
      title: '显示条件',
      key: 'displayFormula',
      index: 1,
      type: 'string',
      value: '',
      isRuleAttribute: 1,
    },
    {
      label: '只读条件',
      title: '只读条件',
      key: 'readonlyCondition',
      index: 2,
      type: 'string',
      value: '',
      isRuleAttribute: 1,
    },
    {
      label: '是否必填',
      title: '是否必填',
      key: 'requiredFormula',
      index: 2,
      type: 'string',
      value: '',
      isRuleAttribute: 1,
    },
  ],
  '10': [
    {
      label: '显示条件',
      title: '显示条件',
      key: 'displayFormula',
      index: 1,
      type: 'string',
      value: '',
      isRuleAttribute: 1,
    },
    {
      label: '只读条件',
      title: '只读条件',
      key: 'readonlyCondition',
      index: 2,
      type: 'string',
      value: '',
      isRuleAttribute: 1,
    },
    {
      label: '是否必填',
      title: '是否必填',
      key: 'requiredFormula',
      index: 2,
      type: 'string',
      value: '',
      isRuleAttribute: 1,
    },
  ],
  '11': [
    {
      label: '显示条件',
      title: '显示条件',
      key: 'displayFormula',
      index: 1,
      type: 'string',
      value: '',
      isRuleAttribute: 1,
    },
    {
      label: '只读条件',
      title: '只读条件',
      key: 'readonlyCondition',
      index: 2,
      type: 'string',
      value: '',
      isRuleAttribute: 1,
    },
    {
      label: '是否必填',
      title: '是否必填',
      key: 'requiredFormula',
      index: 3,
      type: 'string',
      value: '',
      isRuleAttribute: 1,
    },
  ],
  '14': [
    {
      label: '显示条件',
      title: '显示条件',
      key: 'displayFormula',
      index: 1,
      type: 'string',
      value: '',
      isRuleAttribute: 1,
    },
    {
      label: '只读条件',
      title: '只读条件',
      key: 'readonlyCondition',
      index: 2,
      type: 'string',
      value: '',
      isRuleAttribute: 1,
    },
    {
      label: '是否必填',
      title: '是否必填',
      key: 'requiredFormula',
      index: 3,
      type: 'string',
      value: '',
      isRuleAttribute: 1,
    },
  ],
  '15': [
    {
      label: '显示条件',
      title: '显示条件',
      key: 'displayFormula',
      index: 1,
      type: 'string',
      value: '',
      isRuleAttribute: 1,
    },
    {
      label: '只读条件',
      title: '只读条件',
      key: 'readonlyCondition',
      index: 2,
      type: 'string',
      value: '',
      isRuleAttribute: 1,
    },
    {
      label: '是否必填',
      title: '是否必填',
      key: 'requiredFormula',
      index: 2,
      type: 'string',
      value: '',
      isRuleAttribute: 1,
    },
  ],
  '19': [
    {
      label: '选项',
      title: '选项',
      key: 'options',
      index: 1,
      type: 'string',
      value: '',
      isRuleAttribute: 2,
    },
    {
      label: '显示条件',
      title: '显示条件',
      key: 'displayFormula',
      index: 2,
      type: 'string',
      value: '',
      isRuleAttribute: 1,
    },
    {
      label: '只读条件',
      title: '只读条件',
      key: 'readonlyCondition',
      index: 3,
      type: 'string',
      value: '',
      isRuleAttribute: 1,
    },
    {
      label: '是否必填',
      title: '是否必填',
      key: 'requiredFormula',
      index: 4,
      type: 'string',
      value: '',
      isRuleAttribute: 1,
    },
  ],
  '50': [
    {
      label: '映射关系',
      title: '映射关系',
      key: 'mappings',
      index: 1,
      type: 'string',
      value: '',
      isRuleAttribute: 2,
    },
    {
      label: '显示条件',
      title: '显示条件',
      key: 'displayFormula',
      index: 2,
      type: 'string',
      value: '',
      isRuleAttribute: 1,
    },
    {
      label: '只读条件',
      title: '只读条件',
      key: 'readonlyCondition',
      index: 3,
      type: 'string',
      value: '',
      isRuleAttribute: 1,
    },
    {
      label: '是否必填',
      title: '是否必填',
      key: 'requiredFormula',
      index: 4,
      type: 'string',
      value: '',
      isRuleAttribute: 1,
    },
  ],
  '51': [
    {
      label: '显示条件',
      title: '显示条件',
      key: 'displayFormula',
      index: 1,
      type: 'string',
      value: '',
      isRuleAttribute: 1,
    },
    {
      label: '只读条件',
      title: '只读条件',
      key: 'readonlyCondition',
      index: 2,
      type: 'string',
      value: '',
      isRuleAttribute: 1,
    },
    {
      label: '是否必填',
      title: '是否必填',
      key: 'requiredFormula',
      index: 3,
      type: 'string',
      value: '',
      isRuleAttribute: 1,
    },
  ],
  '60': [
    {
      label: '显示条件',
      title: '显示条件',
      key: 'displayFormula',
      index: 1,
      type: 'string',
      value: '',
      isRuleAttribute: 1,
    },
    {
      label: '只读条件',
      title: '只读条件',
      key: 'readonlyCondition',
      index: 2,
      type: 'string',
      value: '',
      isRuleAttribute: 1,
    },
    {
      label: '是否必填',
      title: '是否必填',
      key: 'requiredFormula',
      index: 3,
      type: 'string',
      value: '',
      isRuleAttribute: 1,
    },
  ],
  '61': [
    {
      label: '显示条件',
      title: '显示条件',
      key: 'displayFormula',
      index: 1,
      type: 'string',
      value: '',
      isRuleAttribute: 1,
    },
    {
      label: '只读条件',
      title: '只读条件',
      key: 'readonlyCondition',
      index: 2,
      type: 'string',
      value: '',
      isRuleAttribute: 1,
    },
    {
      label: '是否必填',
      title: '是否必填',
      key: 'requiredFormula',
      index: 3,
      type: 'string',
      value: '',
      isRuleAttribute: 1,
    },
  ],
  '62': [
    {
      label: '映射关系',
      title: '映射关系',
      key: 'mappings',
      index: 1,
      type: 'string',
      value: '',
      isRuleAttribute: 2,
    },
    {
      label: '显示条件',
      title: '显示条件',
      key: 'displayFormula',
      index: 2,
      type: 'string',
      value: '',
      isRuleAttribute: 1,
    },
    {
      label: '只读条件',
      title: '只读条件',
      key: 'readonlyCondition',
      index: 3,
      type: 'string',
      value: '',
      isRuleAttribute: 1,
    },
    {
      label: '是否必填',
      title: '是否必填',
      key: 'requiredFormula',
      index: 4,
      type: 'string',
      value: '',
      isRuleAttribute: 1,
    },
  ],
  '80': [
    {
      label: '显示条件',
      title: '显示条件',
      key: 'displayFormula',
      index: 1,
      type: 'string',
      value: '',
      isRuleAttribute: 1,
    },
    {
      label: '只读条件',
      title: '只读条件',
      key: 'readonlyCondition',
      index: 2,
      type: 'string',
      value: '',
      isRuleAttribute: 1,
    },
    {
      label: '是否必填',
      title: '是否必填',
      key: 'requiredFormula',
      index: 3,
      type: 'string',
      value: '',
      isRuleAttribute: 1,
    },
  ],
  '81': [
    {
      label: '显示条件',
      title: '显示条件',
      key: 'displayFormula',
      index: 1,
      type: 'string',
      value: '',
      isRuleAttribute: 1,
    },
    {
      label: '只读条件',
      title: '只读条件',
      key: 'readonlyCondition',
      index: 2,
      type: 'string',
      value: '',
      isRuleAttribute: 1,
    },
    {
      label: '是否必填',
      title: '是否必填',
      key: 'requiredFormula',
      index: 3,
      type: 'string',
      value: '',
      isRuleAttribute: 1,
    },
  ],
  '100': [
    {
      label: '单据号配置',
      title: '单据号配置',
      key: 'seqNoSetting',
      index: 1,
      type: 'string',
      value: '',
      isRuleAttribute: 2,
    },
  ],
  '101': [
    {
      label: '映射关系',
      title: '映射关系',
      key: 'mappings',
      index: 1,
      type: 'string',
      value: '',
      isRuleAttribute: 2,
    },
  ],

  '102': [],
  '103': [
    {
      label: '映射关系',
      title: '映射关系',
      key: 'mappings',
      index: 1,
      type: 'string',
      value: '',
      isRuleAttribute: 2,
    },
  ],
  '104': [
    {
      label: '默认格式',
      title: '默认格式',
      key: 'format',
      index: 1,
      type: 'string',
      value: '',
      isRuleAttribute: 2,
      isNotShowHis: true,
    },
  ],
  '105': [
    {
      label: '默认格式',
      title: '默认格式',
      key: 'format',
      index: 1,
      type: 'string',
      value: '',
      isRuleAttribute: 2,
      isNotShowHis: true,
    },
  ],
  '106': [
    {
      label: '映射关系',
      title: '映射关系',
      key: 'mappings',
      index: 1,
      type: 'string',
      value: '',
      isRuleAttribute: 2,
    },
  ],
  '109': [
    {
      label: '数据项编码',
      title: '数据项编码',
      key: 'dataItemName',
      index: 1,
      type: 'string',
      value: '',
      isRuleAttribute: 0,
    },
    {
      label: '数据项类型',
      title: '数据项类型',
      key: 'dataItemType',
      index: 2,
      type: 'string',
      value: '',
      isRuleAttribute: 0,
    },
  ],
  '201': [
    {
      label: '空行校验',
      title: '空行校验',
      key: 'isEmptyRow',
      index: 1,
      type: 'string',
      value: '',
      isRuleAttribute: 1,
    },
    {
      label: '显示条件',
      title: '显示条件',
      key: 'displayFormula',
      index: 2,
      type: 'string',
      value: '',
      isRuleAttribute: 1,
    },
  ],
};

export const commonBaseAttributeListMap = {
  '1': [
    {
      label: '绑定数据项编码',
      title: '绑定数据项编码',
      key: 'dataItemName',
      index: 4,
      type: 'string',
      value: '',
      isBaseAttribute: true,
    },
  ],
  '2': [
    {
      label: '绑定数据项编码',
      title: '绑定数据项编码',
      key: 'dataItemName',
      index: 4,
      type: 'string',
      value: '',
      isBaseAttribute: true,
    },
  ],
  '3': [
    {
      label: '绑定数据项编码',
      title: '绑定数据项编码',
      key: 'dataItemName',
      index: 4,
      type: 'string',
      value: '',
      isBaseAttribute: true,
    },
  ],
  '4': [
    {
      label: '绑定数据项编码',
      title: '绑定数据项编码',
      key: 'dataItemName',
      index: 4,
      type: 'string',
      value: '',
      isBaseAttribute: true,
    },
  ],
  '5': [
    {
      label: '绑定数据项编码',
      title: '绑定数据项编码',
      key: 'dataItemName',
      index: 4,
      type: 'string',
      value: '',
      isBaseAttribute: true,
    },
  ],
  '6': [
    {
      label: '绑定数据项编码',
      title: '绑定数据项编码',
      key: 'dataItemName',
      index: 4,
      type: 'string',
      value: '',
      isBaseAttribute: true,
    },
  ],
  '7': [
    {
      label: '绑定数据项编码',
      title: '绑定数据项编码',
      key: 'dataItemName',
      index: 4,
      type: 'string',
      value: '',
      isBaseAttribute: true,
    },
  ],
  '8': [
    {
      label: '绑定数据项编码',
      title: '绑定数据项编码',
      key: 'dataItemName',
      index: 4,
      type: 'string',
      value: '',
      isBaseAttribute: true,
    },
  ],
  '9': [
    {
      label: '绑定数据项编码',
      title: '绑定数据项编码',
      key: 'dataItemName',
      index: 4,
      type: 'string',
      value: '',
      isBaseAttribute: true,
    },
  ],
  '10': [
    {
      label: '绑定数据项编码',
      title: '绑定数据项编码',
      key: 'dataItemName',
      index: 4,
      type: 'string',
      value: '',
      isBaseAttribute: true,
    },
  ],
  '11': [
    {
      label: '绑定数据项编码',
      title: '绑定数据项编码',
      key: 'dataItemName',
      index: 4,
      type: 'string',
      value: '',
      isBaseAttribute: true,
    },
  ],
  '14': [
    {
      label: '绑定数据项编码',
      title: '绑定数据项编码',
      key: 'dataItemName',
      index: 4,
      type: 'string',
      value: '',
      isBaseAttribute: true,
    },
  ],
  '15': [
    {
      label: '绑定数据项编码',
      title: '绑定数据项编码',
      key: 'dataItemName',
      index: 4,
      type: 'string',
      value: '',
      isBaseAttribute: true,
    },
  ],
  '19': [
    {
      label: '绑定数据项编码',
      title: '绑定数据项编码',
      key: 'dataItemName',
      index: 4,
      type: 'string',
      value: '',
      isBaseAttribute: true,
    },
  ],
  '50': [
    {
      label: '绑定数据项编码',
      title: '绑定数据项编码',
      key: 'dataItemName',
      index: 4,
      type: 'string',
      value: '',
      isBaseAttribute: true,
    },
  ],
  '51': [
    {
      label: '绑定数据项编码',
      title: '绑定数据项编码',
      key: 'dataItemName',
      index: 4,
      type: 'string',
      value: '',
      isBaseAttribute: true,
    },
  ],
  '60': [
    {
      label: '绑定数据项编码',
      title: '绑定数据项编码',
      key: 'dataItemName',
      index: 4,
      type: 'string',
      value: '',
      isBaseAttribute: true,
    },
  ],
  '61': [
    {
      label: '绑定数据项编码',
      title: '绑定数据项编码',
      key: 'dataItemName',
      index: 4,
      type: 'string',
      value: '',
      isBaseAttribute: true,
    },
  ],
  '62': [
    {
      label: '绑定数据项编码',
      title: '绑定数据项编码',
      key: 'dataItemName',
      index: 4,
      type: 'string',
      value: '',
      isBaseAttribute: true,
    },
  ],
  '80': [
    {
      label: '绑定数据项编码',
      title: '绑定数据项编码',
      key: 'dataItemName',
      index: 4,
      type: 'string',
      value: '',
      isBaseAttribute: true,
    },
  ],
  '81': [
    {
      label: '绑定数据项编码',
      title: '绑定数据项编码',
      key: 'dataItemName',
      index: 4,
      type: 'string',
      value: '',
      isBaseAttribute: true,
    },
  ],
  '100': [
    {
      label: '绑定数据项编码',
      title: '绑定数据项编码',
      key: 'dataItemName',
      index: 4,
      type: 'string',
      value: '',
      isBaseAttribute: true,
    },
  ],
  '101': [
    {
      label: '绑定数据项编码',
      title: '绑定数据项编码',
      key: 'dataItemName',
      index: 4,
      type: 'string',
      value: '',
      isBaseAttribute: true,
    },
  ],
  '102': [
    {
      label: '绑定数据项编码',
      title: '绑定数据项编码',
      key: 'dataItemName',
      index: 4,
      type: 'string',
      value: '',
      isBaseAttribute: true,
    },
  ],
  '103': [
    {
      label: '绑定数据项编码',
      title: '绑定数据项编码',
      key: 'dataItemName',
      index: 4,
      type: 'string',
      value: '',
      isBaseAttribute: true,
    },
  ],
  '104': [
    {
      label: '绑定数据项编码',
      title: '绑定数据项编码',
      key: 'dataItemName',
      index: 4,
      type: 'string',
      value: '',
      isBaseAttribute: true,
    },
  ],
  '105': [
    {
      label: '绑定数据项编码',
      title: '绑定数据项编码',
      key: 'dataItemName',
      index: 4,
      type: 'string',
      value: '',
      isBaseAttribute: true,
    },
  ],
  '106': [
    {
      label: '绑定数据项编码',
      title: '绑定数据项编码',
      key: 'dataItemName',
      index: 4,
      type: 'string',
      value: '',
      isBaseAttribute: true,
    },
  ],
  '109': [
    {
      label: '绑定数据项编码',
      title: '绑定数据项编码',
      key: 'dataItemName',
      index: 4,
      type: 'string',
      value: '',
      isBaseAttribute: true,
    },
  ],
  '201': [
    {
      label: '绑定数据项编码',
      title: '绑定数据项编码',
      key: 'dataItemName',
      index: 4,
      type: 'string',
      value: '',
      isBaseAttribute: true,
    },
  ],
};
