/*
禁止修改!此文件是产品代码的一部分，后续可能变更或者不再开放。
若有问题，请参考前端相关二开文档。
*/
const mockDefaultPortal = {
  customAction: {
    names: ['onPageEnter'],
    script:
      '/**\n * 页面js动作，会在页面事件加载完成时调用\n * 自定义事件需要写在onPageEnter方法中\n * 请不要删除onPageEnter方法,否则自定义事件不执行\n *  */\nfunction onPageEnter() {\n\n}',
  },
  customStyle: '',
  designer: {
    defaultPortalDashboard: {
      layout: {},
      id: 'defaultPortalDashboard',
      type: 'Page',
      name: '',
      parentId: null,
      childIds: [
        'RowMenu1',
        'Carousel1',
        'MyApplication1',
        'MyUnfinished1',
        'ShortcutList1',
      ],
      cloneable: true,
      removable: true,
      immutable: false,
      version: '0.0.1',
      props: {
        size: { width: '', height: '100%' },
        padding: { top: '0px', bottom: '0px', left: '0px', right: '0px' },
        background: {
          color: '#ffffff',
          image: '',
          position: '',
          size: '',
          repeat: '',
          attachment: '',
        },
        overflow: { x: 'auto', y: 'auto' },
        visible: { show: true, opacity: 1 },
      },
      eventHandlers: {
        enter: [{ type: 'custom', argu: 'onPageEnter', name: 'onPageEnter' }],
      },
      bindings: {},
    },
    RowMenu1: {
      layout: { left: 0, top: 0, width: 12, height: 9 },
      id: 'RowMenu1',
      type: 'RowMenu',
      name: '',
      parentId: 'defaultPortalDashboard',
      childIds: [],
      cloneable: true,
      removable: true,
      immutable: false,
      version: '',
      props: {
        navigator: [
          {
            icon: 'h-icon-all-workbench',
            title: '{"zh": "工作台","en": "Dashboard"}',
            actionType: 'portalPage',
            portalPage: 'defaultPortalDashboard',
            isDefaultWorkbench: true,
            openMode: 'curPage',
            length: 6,
          },
          {
            icon: 'h-icon-all-a-technologicalprocess',
            title: '{"zh": "流程中心","en": "Workflow Center"}',
            actionType: 'portalPage',
            portalPage: 'defaultWorkflowCenter',
            URL: '',
            openMode: 'curPage',
            length: 8,
          },
          {
            icon: 'h-icon-all-application',
            title: '{"zh": "应用列表","en": "Apps"}',
            actionType: 'portalPage',
            portalPage: 'defaultApplicationList',
            URL: '',
            openMode: 'curPage',
            length: 8,
          },
        ],
      },
      eventHandlers: {},
      bindings: {},
    },
    Carousel1: {
      layout: { left: 1, top: 9, width: 10, height: 51 },
      id: 'Carousel1',
      type: 'Carousel',
      name: '',
      parentId: 'defaultPortalDashboard',
      childIds: [],
      cloneable: true,
      removable: true,
      immutable: false,
      version: '',
      props: {
        backgroundColor: 'rgba(255,255,255,1)',
        borderRadius: 'medium',
        borderStyle: 'none',
        borderThickness: 1,
        borderColor: '#E4E7EE',
        photos: [
          {
            name: '图片1',
            tempUrl: '',
            openType: '_blank',
            fillType: 'Scale',
            gotoType: 3,
            app: '',
            bizModel: '',
            linkUrl: 'https://www.yuque.com/skwme4/hyk0u0/tyozqyvl3i318uw7',
            gotoPage: 'defaultPortalDashboard',
          },
        ],
        autoplay: true,
      },
      eventHandlers: {},
      bindings: {},
    },
    MyApplication1: {
      layout: { left: 1, top: 60, width: 10, height: 48 },
      id: 'MyApplication1',
      type: 'MyApplication',
      name: '',
      parentId: 'defaultPortalDashboard',
      childIds: [],
      cloneable: false,
      removable: true,
      immutable: false,
      version: '',
      props: {
        backgroundColor: 'rgba(255,255,255,1)',
        backgroundImg: '',
        borderRadius: 'medium',
        borderStyle: 'none',
        borderThickness: 1,
        borderColor: '#E4E7EE',
        textColor: '#111218',
        textThickness: 'normal',
      },
      eventHandlers: {},
      bindings: {},
    },
    MyUnfinished1: {
      layout: { left: 1, top: 108, width: 6, height: 47 },
      id: 'MyUnfinished1',
      type: 'MyUnfinished',
      name: '',
      parentId: 'defaultPortalDashboard',
      childIds: [],
      cloneable: false,
      removable: true,
      immutable: false,
      version: '',
      props: {
        backgroundColor: 'rgba(255,255,255,1)',
        backgroundImg: '',
        borderRadius: 'medium',
        borderStyle: 'none',
        borderThickness: 1,
        borderColor: '#E4E7EE',
        textColor: '#111218',
        textThickness: 'normal',
      },
      eventHandlers: {},
      bindings: {},
    },
    ShortcutList1: {
      layout: { left: 7, top: 108, width: 4, height: 47 },
      id: 'ShortcutList1',
      type: 'ShortcutList',
      name: '',
      parentId: 'defaultPortalDashboard',
      childIds: [],
      cloneable: false,
      removable: true,
      immutable: false,
      version: '',
      props: {
        backgroundColor: 'rgba(255,255,255,1)',
        backgroundImg: '',
        borderRadius: 'medium',
        borderStyle: 'none',
        borderThickness: 1,
        borderColor: '#E4E7EE',
        textColor: '#111218',
        textThickness: 'normal',
      },
      eventHandlers: {},
      bindings: {},
    },
  },
};

export default mockDefaultPortal;
